on:
  workflow_dispatch:
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: list files in home directory
        run: ls -al /home
  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: save output to file
        run: ls -al /home > asd.txt
        
  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: view file content
        run: |
          ls -al /home > asd.txt
          cat asd.txt
          
  job_4:
    runs-on: ubuntu-latest
    needs: [job_2,job_3]
    steps:
      - name: clear lab files
        run: |
          ls -al /home > asd.txt
          cat asd.txt
          rm -rf asd.txt
