name: First workflow

on:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: ls -altr
      - name: checkout repo
        uses: actions/checkout@v4.2.2
      - name: list new files
        run: ls -altr
     
