name: First workflow

on:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: test installed docker
        run: |
          docker version
          docker run -d nginx 
          docker ps -a
      - name: list files
        run: ls -altr
      - name: checkout repo
        uses: actions/checkout@v4.2.2
      - name: list new files
        run: ls -altr
     
