on:
  workflow_dispatch:
    inputs:
        environment:
          description: 'Environment to run the job'
          required: true
          type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to environment
        run: echo "Deploying to ${{ inputs.environment }} environment"
