on:
    push:
        branches:
            - main
            - "release/**"
        paths:
            - "src/**"
    pull_request:
        branches: 
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v4.2.2
        - name: run test
          run: npm test