on:
    repository_dispatch:
        types: [run-tests]
jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
            - name: run tests
              run: echo "<<<---- Running tests ---->>>"